# Generated by Django 5.1.2 on 2024-11-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="alt",
            field=models.CharField(default="1", max_length=100, verbose_name="alt"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="1", upload_to="posts/%Y/%m/%d", verbose_name="image"
            ),
            preserve_default=False,
        ),
    ]
