volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}
  production_django_static: {}



services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: django_site
    volumes:
      - production_django_media:/app/media
      - production_django_static:/app/staticfiles
    depends_on:
      - postgres
      - valkey
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: postgres_site
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  valkey:
    image: docker.io/valkey/valkey:latest


  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: nginx_site
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/src/app/media:ro
      - production_django_static:/usr/src/app/staticfiles
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
